#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# 一次性設定：產生 release 簽章金鑰並登記成 GitHub Actions secret。
#
# 這是 **bash** 腳本，不是 PowerShell —— 要用 Git Bash 跑，cmd 與 PowerShell
# 都無法直接執行（用法見 README 發佈章節）。tools/ 裡其他兩支是 .ps1，
# 這支之所以是 bash，是因為它要呼叫 keytool 與 gh 並處理 base64 管線，
# 而 PS 5.1 會把二進位管線當文字處理弄壞 base64。
#
# 畫面輸出刻意全是 ASCII 英文：從 cmd/PowerShell 呼叫 bash.exe 時，
# 主控台的 codepage 常常不是 UTF-8，中文會變成亂碼。註解則照專案慣例寫中文。

TOTAL_STAGES=6

# 從腳本自己的位置推出專案根目錄，不要寫死絕對路徑 ——
# 這支腳本存在的意義就是換機器重建，寫死路徑等於第一次用就壞。
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JKS="$PROJECT_ROOT/release.jks"
# keystore.properties 的格式剛好就是 KEY=VALUE，所以直接讓 write_env 寫它。
# 這個檔已經在 .gitignore 裡，不會進版控。
ENV_FILE="$PROJECT_ROOT/keystore.properties"

cd "$PROJECT_ROOT"

banner "NutriLog release signing"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "This creates the signing key that every future NutriLog release is"
say "signed with, and registers it with GitHub Actions."
printf '\n'
warn "Read this before continuing:"
note "  Android refuses to install an update signed with a different key."
note "  Once you ship a release signed with THIS key, you must keep the key"
note "  forever. Lose it and the only way to ship an update is to make users"
note "  uninstall first -- which wipes every meal they ever logged, because"
note "  this app stores everything locally with no cloud backup."
printf '\n'

JAVA_HOME_DEFAULT="C:/Program Files/Eclipse Adoptium/jdk-17.0.7.7-hotspot"
KEYTOOL="${JAVA_HOME:-$JAVA_HOME_DEFAULT}/bin/keytool"
[[ -x "$KEYTOOL" ]] || KEYTOOL="$JAVA_HOME_DEFAULT/bin/keytool"
# keytool follows the system locale -- Big5 on this machine, which renders as
# mojibake in a UTF-8 terminal. An unreadable error is worse than none.
KT_LANG=(-J-Duser.language=en -J-Duser.country=US)
if [[ ! -x "$KEYTOOL" ]]; then
  printf '  %s✗%s keytool not found at %s\n' "$RED" "$RESET" "$KEYTOOL"
  say "Install JDK 17 or set JAVA_HOME, then re-run."
  exit 1
fi
printf '  %s✓%s keytool: %s\n' "$GREEN" "$RESET" "$KEYTOOL"

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  printf '  %s✓%s gh authenticated (%s)\n' "$GREEN" "$RESET" "$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || echo 'repo unknown')"
else
  warn "gh not authenticated -- stage 5 will tell you what to set by hand."
fi
printf '\n'
pause "Press Enter to continue"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the keystore"

if [[ -f "$JKS" ]]; then
  warn "release.jks already exists at $JKS"
  note "Overwriting it means every APK already signed with the old key becomes"
  note "un-updatable. If you are not certain it is unused, answer No."
  if ! confirm "Overwrite the existing release.jks?"; then
    say "Keeping the existing keystore. Skipping to verification."
    SKIP_CREATE=1
  fi
fi

if [[ -z "${SKIP_CREATE:-}" ]]; then
  say "Answer a few questions; the key is generated locally and never leaves"
  say "this machine except as an encrypted GitHub secret."
  printf '\n'
  ask keyAlias "Key alias [nutrilog]:"
  [[ -n "$keyAlias" ]] || keyAlias="nutrilog"
  CN_DEFAULT="$(git config user.name 2>/dev/null || true)"
  [[ -n "$CN_DEFAULT" ]] || CN_DEFAULT="NutriLog"
  ask CERT_CN "Your name or org for the certificate [$CN_DEFAULT]:"
  [[ -n "$CERT_CN" ]] || CERT_CN="$CN_DEFAULT"
  printf '\n'
  note "A .jks created by JDK 17 is PKCS12, which cannot hold a separate key"
  note "password -- so one password protects both. Use a real one and put it in"
  note "your password manager now; there is no recovery."
  printf '\n'
  while :; do
    ask_secret KS_PASS_1 "Keystore password (min 6 chars):"
    if [[ ${#KS_PASS_1} -lt 6 ]]; then
      warn "too short -- keytool requires at least 6 characters."
      continue
    fi
    ask_secret KS_PASS_2 "Type it again:"
    [[ "$KS_PASS_1" == "$KS_PASS_2" ]] && break
    warn "the two entries did not match -- try again."
  done
  storePassword="$KS_PASS_1"
  unset KS_PASS_1 KS_PASS_2

  printf '\n'
  # Passwords go through the environment, not argv: anything on the command
  # line shows up in the process list for every other user on the machine.
  KS_PASS="$storePassword" "$KEYTOOL" "${KT_LANG[@]}" -genkeypair \
    -keystore "$JKS" \
    -alias "$keyAlias" \
    -keyalg RSA -keysize 2048 \
    -validity 10000 \
    -storepass:env KS_PASS \
    -keypass:env KS_PASS \
    -dname "CN=$CERT_CN, OU=NutriLog, O=NutriLog, C=TW"

  printf '  %s✓%s created %s\n' "$GREEN" "$RESET" "$JKS"
fi
printf '\n'
pause "Press Enter to continue"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Verify the keystore"

if [[ -z "${storePassword:-}" ]]; then
  say "Confirm the password for the existing keystore."
  ask_secret storePassword "Keystore password:"
fi
if [[ -z "${keyAlias:-}" ]]; then
  ask keyAlias "Key alias:"
fi

say "Certificate fingerprint -- record this somewhere; it is how you prove"
say "later that an APK really came from you."
printf '\n'
if ! KS_PASS="$storePassword" "$KEYTOOL" "${KT_LANG[@]}" -list -v \
      -keystore "$JKS" -alias "$keyAlias" -storepass:env KS_PASS \
      2>/dev/null | grep -E "SHA-?256|Valid from"; then
  printf '  %s✗%s could not read the keystore -- wrong password or alias?\n' "$RED" "$RESET"
  exit 1
fi
printf '\n'
printf '  %s✓%s keystore verified\n' "$GREEN" "$RESET"
printf '\n'
pause "Press Enter to continue"

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Local signed builds"

say "Writing keystore.properties so local 'assembleRelease' produces an APK"
say "signed with the SAME key as CI. Without it, local release builds fall"
say "back to a debug signature and cannot overwrite a CI-built install."
printf '\n'
write_env storeFile "release.jks"
write_env storePassword "$storePassword"
write_env keyAlias "$keyAlias"
write_env keyPassword "$storePassword"
printf '\n'
note "keystore.properties and release.jks are both gitignored -- verifying:"
# 一次一個路徑：git check-ignore 的 -q 配上多個路徑會直接 fatal，
# 於是 if 判定失敗，明明有被忽略卻報成「沒被忽略」。
if git check-ignore -q keystore.properties && git check-ignore -q release.jks; then
  printf '  %s✓%s both are ignored by git\n' "$GREEN" "$RESET"
else
  warn "NOT ignored by git -- do not commit until you fix .gitignore!"
fi
printf '\n'
pause "Press Enter to continue"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "GitHub Actions secrets"

say "CI rebuilds the keystore from a base64 copy of release.jks."
printf '\n'
if command -v base64 >/dev/null 2>&1; then
  KEYSTORE_B64=$(base64 -w 0 "$JKS" 2>/dev/null || base64 "$JKS" | tr -d '\n')
else
  printf '  %s✗%s base64 not available\n' "$RED" "$RESET"
  exit 1
fi
note "encoded ${#KEYSTORE_B64} characters"
printf '\n'
set_secret KEYSTORE_BASE64 "$KEYSTORE_B64"
set_secret STORE_PASSWORD  "$storePassword"
set_secret KEY_ALIAS       "$keyAlias"
set_secret KEY_PASSWORD    "$storePassword"
unset KEYSTORE_B64
printf '\n'
if confirm "Open the repo secrets page to confirm all four landed?"; then
  # 從 remote 問出 repo，別寫死帳號名
  REPO_SLUG="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)"
  if [[ -n "$REPO_SLUG" ]]; then
    open_url "https://github.com/$REPO_SLUG/settings/secrets/actions"
  else
    warn "could not resolve the repo -- open Settings > Secrets and variables > Actions by hand."
  fi
fi
printf '\n'
pause "Press Enter to continue"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Back up the key"

warn "Do this now, not later."
printf '\n'
say "Copy release.jks somewhere that survives this machine dying:"
note "  $JKS"
printf '\n'
say "A password manager attachment or an encrypted cloud folder both work."
say "Do NOT put it in the git repo -- it is gitignored for a reason."
printf '\n'
note "The GitHub secret is a usable backup too, but it is write-only:"
note "you can never read it back out, so it does not count as one."
printf '\n'
pause "Press Enter once the key is backed up"

finish

printf '  %sNext:%s tag the release --\n\n' "$BOLD" "$RESET"
printf '      git tag -a v1.0 -m "First release"\n'
printf '      git push origin v1.0\n\n'
printf '  %sCI will build a properly signed APK and publish it as a Release.%s\n\n' "$DIM" "$RESET"
