#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


# 一次性設定：在 Google Cloud 建立 OAuth client，讓 app 能寫進使用者的 Drive。
#
# 這支腳本**不會**在 repo 裡留下任何值 —— Android 的 OAuth client 是靠
# 「套件名 + 簽章 SHA-1」認的，client id 不需要進 app 也不需要進版控。
# 所以它的工作是：算出兩組 SHA-1、把 Console 的頁面一頁一頁打開、
# 告訴你每一頁要填什麼。
#
# 這是 **bash** 不是 PowerShell，要用 Git Bash 跑（同 setup-signing.sh）。
# 畫面輸出全 ASCII 英文：從 cmd/PowerShell 呼叫 bash.exe 時主控台
# codepage 常常不是 UTF-8，中文會變亂碼。註解照專案慣例寫中文。

TOTAL_STAGES=8

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

PACKAGE_NAME="com.watson.nutrilog"
DEBUG_SHA1=""
RELEASE_SHA1=""

# keytool 印的已經是 AA:BB:.. 格式；apksigner 印的是一長串小寫 hex，要自己補冒號。
colonise() {
  printf '%s' "$1" | tr 'a-f' 'A-F' | sed 's/../&:/g; s/:$//'
}

find_keytool() {
  if [[ -n "${JAVA_HOME:-}" && -x "$JAVA_HOME/bin/keytool" ]]; then
    printf '%s' "$JAVA_HOME/bin/keytool"
  elif command -v keytool >/dev/null 2>&1; then
    printf '%s' "keytool"
  fi
}

# build-tools 可能裝了好幾版，取最新的那一個。
find_apksigner() {
  local sdk="${ANDROID_HOME:-${LOCALAPPDATA:-$HOME}/Android/Sdk}"
  local found
  found=$(ls -d "$sdk"/build-tools/*/apksigner* 2>/dev/null | sort -V | tail -1) || true
  [[ -n "$found" ]] && printf '%s' "$found"
  # 找不到不是錯誤（只有 release 指紋用得到），但函式回傳值會被 set -e 當成失敗
  return 0
}

banner "NutriLog Google Drive backup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "This registers an Android OAuth client so NutriLog can back up to your"
say "own Google Drive. Nothing is written into this repo: an Android OAuth"
say "client is identified by package name + signing SHA-1, so there is no"
say "client id or secret to store anywhere."
printf '\n'
KEYTOOL=$(find_keytool)
if [[ -z "$KEYTOOL" ]]; then
  warn "keytool not found. Set JAVA_HOME to your JDK 17 and re-run."
  exit 1
fi
say "keytool: $KEYTOOL"
APKSIGNER=$(find_apksigner)
if [[ -n "$APKSIGNER" ]]; then
  say "apksigner: $APKSIGNER"
else
  note "apksigner not found (only needed for the release fingerprint)"
fi
printf '\n'
note "You need a Google account. A Cloud project is free for this use."
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Debug signing fingerprint"
say "The debug keystore is what every locally built APK is signed with."
say "Without this fingerprint registered, sign-in fails on your own builds."
printf '\n'
DEBUG_KS="$HOME/.android/debug.keystore"
if [[ -f "$DEBUG_KS" ]]; then
  DEBUG_SHA1=$("$KEYTOOL" -list -v -keystore "$DEBUG_KS" -alias androiddebugkey \
    -storepass android -keypass android 2>/dev/null \
    | grep -i "SHA1:" | head -1 | sed 's/.*SHA1: *//' | tr -d '\r') || true
fi
if [[ -n "$DEBUG_SHA1" ]]; then
  printf '  %sdebug SHA-1:%s %s\n' "$BOLD" "$RESET" "$DEBUG_SHA1"
else
  warn "no debug keystore yet at $DEBUG_KS"
  note "Build the app once (gradle assembleDebug) and re-run this stage."
fi
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Release signing fingerprint"
say "The release APK is signed by CI with the key in the GitHub secrets."
say "GitHub secrets are write-only, so we cannot read the keystore back."
say "Two ways to get the fingerprint instead:"
printf '\n'
if [[ -f "$PROJECT_ROOT/release.jks" && -f "$PROJECT_ROOT/keystore.properties" ]]; then
  say "Found a local release.jks - reading it directly."
  KS_ALIAS=$(grep -E '^keyAlias=' "$PROJECT_ROOT/keystore.properties" | cut -d= -f2- | tr -d '\r') || true
  KS_PASS=$(grep -E '^storePassword=' "$PROJECT_ROOT/keystore.properties" | cut -d= -f2- | tr -d '\r') || true
  RELEASE_SHA1=$("$KEYTOOL" -list -v -keystore "$PROJECT_ROOT/release.jks" -alias "$KS_ALIAS" \
    -storepass "$KS_PASS" 2>/dev/null | grep -i "SHA1:" | head -1 | sed 's/.*SHA1: *//' | tr -d '\r') || true
elif [[ -n "$APKSIGNER" ]] && command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  say "No local keystore - reading the fingerprint out of the published APK."
  TMP_APK_DIR=$(mktemp -d)
  if gh release download --pattern '*.apk' --dir "$TMP_APK_DIR" >/dev/null 2>&1; then
    APK=$(ls "$TMP_APK_DIR"/*.apk 2>/dev/null | head -1) || true
    RAW=$("$APKSIGNER" verify --print-certs "$APK" 2>/dev/null \
      | grep -i "SHA-1 digest" | head -1 | sed 's/.*: *//' | tr -d '\r') || true
    [[ -n "$RAW" ]] && RELEASE_SHA1=$(colonise "$RAW")
  fi
  rm -rf "$TMP_APK_DIR"
fi
if [[ -n "$RELEASE_SHA1" ]]; then
  printf '  %srelease SHA-1:%s %s\n' "$BOLD" "$RESET" "$RELEASE_SHA1"
else
  warn "could not determine the release fingerprint automatically"
  note "Either run tools/setup-signing.sh on this machine, or download a"
  note "release APK and run: apksigner verify --print-certs NutriLog-*.apk"
  note "You can register it later - debug builds will work without it."
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Google Cloud project"
say "Create a project to own the OAuth client (or reuse one you have)."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it anything - NutriLog is fine. No organisation needed."
step "Wait for it to finish creating, then make sure it is the SELECTED"
step "project in the picker at the top of the page."
warn "Every later stage acts on the selected project. Check the picker."
pause "Project created and selected?"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Enable the Drive API"
say "Without this the app gets a 403 the first time it tries to upload."
open_url "https://console.cloud.google.com/apis/library/drive.googleapis.com"
step "Press ENABLE. If it already says MANAGE, it is on - move along."
pause "Drive API enabled?"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Consent screen"
say "This is the screen the phone shows when you tap Connect Google Drive."
open_url "https://console.cloud.google.com/auth/overview"
step "Fill in an app name and your own email as support + developer contact."
step "Audience: choose External."
note "Google renames this area every so often (it used to be OAuth consent"
note "screen, now Google Auth platform). Follow the wording you actually see"
note "- what matters is: External audience, app name, contact email."
pause "Consent screen configured?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Scope and test user"
say "Only ONE scope is needed, and it is deliberately the narrow one."
open_url "https://console.cloud.google.com/auth/scopes"
step "Add scope: https://www.googleapis.com/auth/drive.file"
note "drive.file = see and manage only files this app created. It is NOT a"
note "restricted scope, so you do NOT need Google's paid security assessment."
note "Do not add drive or drive.readonly - those do need it."
printf '\n'
open_url "https://console.cloud.google.com/auth/audience"
step "While the app is in Testing, add YOUR OWN Google account as a test user."
warn "Skipping this is the most common cause of access blocked at sign-in."
pause "Scope added and yourself added as a test user?"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Android OAuth client"
say "Last step: the client itself. Both fingerprints go here."
open_url "https://console.cloud.google.com/auth/clients"
step "CREATE CLIENT, then Application type: Android"
printf '\n'
printf '  %sPackage name:%s %s\n' "$BOLD" "$RESET" "$PACKAGE_NAME"
[[ -n "$DEBUG_SHA1" ]]   && printf '  %sSHA-1 (debug):%s   %s\n' "$BOLD" "$RESET" "$DEBUG_SHA1"
[[ -n "$RELEASE_SHA1" ]] && printf '  %sSHA-1 (release):%s %s\n' "$BOLD" "$RESET" "$RELEASE_SHA1"
printf '\n'
warn "One client holds ONE fingerprint. Create a second Android client with"
warn "the same package name for the other SHA-1 - debug builds and released"
warn "builds are signed differently, and only the registered one will work."
note "Changes can take a few minutes to take effect."
pause "Client(s) created?"

finish
printf '  %sTry it:%s build and install a debug APK, open Settings, scroll to\n' "$BOLD" "$RESET"
printf '  the cloud backup section and tap Connect Google Drive.\n'
printf '  Expect: a Google account chooser, then a one-line consent screen.\n\n'
printf '  %sIf sign-in fails:%s the fingerprint you registered does not match the\n' "$BOLD" "$RESET"
printf '  APK you installed. Re-run this wizard and compare the values.\n\n'
